export { default as HomePage} from "./HomePage"
export { default as FormFrame} from "./form/FormFrame"
export { default as FormFDrop} from "./form/FormDrop"
export { default as FormSignIn} from "./form/FormSignIn"
export { default as FormLogIn} from "./form/FormLogIn"
export { EmailBox, FormBox, PassBox, ConfirmPassBox, Submit, NameBox } from "./form/CommonFormComp"